export enum ActionType {
  CURRENT_THEME = "CURRENT_THEME",
  CONNECT_WALLET = "CONNECT_WALLET",
  CONNECT_WALLET_ERROR = "CONNECT_WALLET_ERROR",
  CONNECT_WALLET_SUCCESS = "CONNECT_WALLET_SUCCESS",
  DEPOSIT_AMOUNT = "DEPOSIT_AMOUNT"
}
